import React, { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { NativeStackScreenProps } from "@react-navigation/native-stack";
import { api } from "../api/client";
import { colors } from "../constants/theme";
import type { RootStack } from "../types";

const labels: Record<string,string>={Name:"Record Number",Asset_Code__c:"Asset Code",Asset_Name__c:"Asset Name",Status__c:"Status",Given_Date__c:"Given Date",Competitor_Name__c:"Competitor",Company__c:"Company",MRP__c:"MRP",RBP__c:"Retail Buying Price",Scheme_Details__c:"Scheme",Subject__c:"Subject",Description__c:"Description",Quantity__c:"Quantity",Manufacturing_Date__c:"Manufacturing Date",Return_Reason__c:"Return Reason",outletName:"Outlet",visitName:"Visit",productName:"Product"};
export default function ModuleListScreen({route}:NativeStackScreenProps<RootStack,"ModuleList">){
 const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=()=>{setLoading(true);setError("");api<any[]>(`/modules/${route.params.moduleName}`).then(setRows).catch(e=>setError(e.message)).finally(()=>setLoading(false));};
 useEffect(load,[route.params.moduleName]);
 return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.title}>{route.params.title}</Text><Text style={s.sub}>Live Salesforce records for your outlets</Text>{loading&&<ActivityIndicator color={colors.brand} style={s.loader}/>} {!!error&&<Pressable style={s.error} onPress={load}><Text style={s.errorTitle}>{error}</Text><Text style={s.retry}>TAP TO RETRY</Text></Pressable>}{!loading&&!error&&!rows.length&&<View style={s.empty}><Text style={s.recordTitle}>No records found</Text><Text style={s.sub}>Records created from outlet visits will appear here.</Text></View>}{rows.map(row=><View key={row.Id} style={s.card}><Text style={s.recordTitle}>{row.Name||row.Subject__c||"Salesforce record"}</Text>{Object.entries(row).filter(([key,value])=>key!=="Id"&&key!=="Name"&&value!==null&&value!==undefined&&value!=="").map(([key,value])=><View key={key} style={s.field}><Text style={s.label}>{labels[key]||key.replace(/__c$/,"").replaceAll("_"," ")}</Text><Text style={s.value}>{typeof value==="number"&&["MRP__c","RBP__c"].includes(key)?`₹${value}`:String(value)}</Text></View>)}</View>)}</ScrollView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.surface},content:{padding:16},title:{fontSize:24,fontWeight:"900",color:colors.navy},sub:{fontSize:11,color:colors.muted,marginTop:4},loader:{marginTop:30},card:{backgroundColor:"white",borderRadius:16,padding:15,marginTop:12,borderLeftWidth:4,borderLeftColor:"#9DD9C9"},recordTitle:{fontSize:15,fontWeight:"900",color:colors.ink,marginBottom:8},field:{flexDirection:"row",justifyContent:"space-between",borderTopWidth:1,borderTopColor:colors.border,paddingVertical:7,gap:10},label:{fontSize:10,color:colors.muted,textTransform:"capitalize",flex:1},value:{fontSize:11,color:colors.ink,fontWeight:"700",flex:1,textAlign:"right"},empty:{alignItems:"center",padding:30,marginTop:20},error:{backgroundColor:"#FFF0F1",padding:15,borderRadius:12,marginTop:16},errorTitle:{color:colors.danger,fontWeight:"800"},retry:{color:colors.brand,fontWeight:"900",fontSize:10,marginTop:8}});
